version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks: 
      - app-network

  back:
      container_name: nestjs_api_dev
      image: back-end
      build: ./back-end
      volumes:
        - ./back-end:/usr/app
        - /usr/app/node_modules
      ports:
        - 3000:3000
      networks: 
        - app-network

networks:
  app-network:
    driver: bridge
volumes:
    esdata1:
      driver: local